### ISSUE TITLE
How to set default value for _isFavorite

### ISSUE THREAD

**Issue by Sureya** [TeaTalkInternal/favorite_button#1]
If a user has already added something as a favorite how do we implement that by setting the default value of _isFavorite=True in the following code?

```
FavoriteButton(
	iconSize: 8,
	iconColor: Colors.redAccent,
	valueChanged: (_isFavorite) {
	  print('Is Favorite : $_isFavorite');
	},
)
```

**Comment by KevinVishalSaldanha** [comment]
Thanks Sureya for the catch. Il need to update this, il see if i can fix it at the earliest

**Comment by KevinVishalSaldanha** [comment]
> If a user has already added something as a favorite how do we implement that by setting the default value of _isFavorite=True in the following code?
> 
> ```
> FavoriteButton(
> 	iconSize: 8,
> 	iconColor: Colors.redAccent,
> 	valueChanged: (_isFavorite) {
> 	  print('Is Favorite : $_isFavorite');
> 	},
> )
> ```

Thanks Sureya for the catch. Il need to update this, il see if i can fix it at the earliest

**Comment by vishalkevin11** [comment]
> If a user has already added something as a favorite how do we implement that by setting the default value of _isFavorite=True in the following code?
> 
> ```
> FavoriteButton(
> 	iconSize: 8,
> 	iconColor: Colors.redAccent,
> 	valueChanged: (_isFavorite) {
> 	  print('Is Favorite : $_isFavorite');
> 	},
> )
> ```

Thanks Sureya for the catch. Il need to update this, il see if i can fix it at the earliest

**Comment by Sureya** [comment]
@vishalkevin11 : did you get a chance to fix this please ?

**Comment by vishalkevin11** [comment]
> @vishalkevin11 : did you get a chance to fix this please ?

Yea just did, Please use `favorite_button: ^0.0.3` , This is updated . You may pass `isFavorite` or `isStarred`  for **Favorite** or **Star** button respectively.

**Comment by Sureya** [comment]
@vishalkevin11 : Many thanks for the update. I can confirm that the feature is working as expected. Amazing library!

Thanks again for the quick support! 👍
