### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by brhomapps** [TeaTalkInternal/favorite_button#4]
hi, Ms/TeaTalk 

when i add favorite button in listview with listTile ,i press the heart icon and the color change to red but when i move the listview up and down the color red is Disappears..please help me and thanks

**Comment by brhomapps** [comment]
`        ListView(children: <Widget>[ Container(
            padding: EdgeInsets.all(2),
            margin: const EdgeInsets.all(4.0),
            decoration: BoxDecoration(border: Border.all(color: Colors.grey)),
            child: ListTile(
              selected: true,
              leading: Container(
                color: Colors.blue,
                child: Image.asset(
                  'assets/appsmaker.png',
                  fit: BoxFit.contain,
                ),
              ),
              trailing: FavoriteButton(
                isFavorite: false,
                valueChanged: (_isFavorite) {
                  print('Is Favorite : $_isFavorite');
                },
              ),
              title: Text(
                'title of items you wont',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
              ),
              subtitle: Text('some describtion'),
            ),
          ),])
`

**Comment by vishalkevin11** [comment]
Hi @brhomapps ,

The issue I see is the state for `isFavorite` is not retained . You will have to hold this in a variable. Since the `listview` redraws when its `listitems`  move above or below the screen, the `isFavorite` state is lost.

Try this way instead
`class MyApp extends StatefulWidget {
  // This widget is the root of your application.

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _allfavorites = [
    {'id': '0000_key', 'isFav': false},
    {'id': '0001_key', 'isFav': false},
    {'id': '0002_key', 'isFav': false},
    {'id': '0003_key', 'isFav': false},
    {'id': '0004_key', 'isFav': false},
    {'id': '0005_key', 'isFav': false},
    {'id': '0006_key', 'isFav': false},
    {'id': '0007_key', 'isFav': false},
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
          appBar: AppBar(
            title: Text('Home'),
          ),
          body: ListView.builder(
            itemBuilder: _buildlistTitleWidget,
            itemCount: _allfavorites.length,
          )),
    );
  }

  Widget _buildlistTitleWidget(BuildContext context, int index) {
    var favObj = _allfavorites[index];
    return Container(
      padding: EdgeInsets.all(2),
      margin: const EdgeInsets.all(4.0),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.grey),
      ),
      child: ListTile(
        selected: true,
        leading: Container(
          color: Colors.blue,
          child: Image.asset(
            'assets/appsmaker.png',
            fit: BoxFit.contain,
          ),
        ),
        trailing: FavoriteButton(
          key: Key(favObj['id'] as String),
          isFavorite: favObj['isFav'] as bool,
          valueChanged: (_isFavorite) {
            print('Is Favorite : $_isFavorite');
            favObj['isFav'] = _isFavorite;
            setState(() {
              _allfavorites[index] = favObj;
            });
          },
        ),
        title: Text(
          'title of items you id ${favObj['id'] as String}',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
        ),
        subtitle: Text('some describtion'),
      ),
    );
  }
}
`
